import React from "react";
import styles from "./Disclaimer.module.css"; // Import CSS module
import { cn } from "@/lib/utils";

interface DisclaimerProps {
  className?: string;
  // Add other props if needed
}

const Disclaimer: React.FC<DisclaimerProps> = ({ className }) => {
  return (
    <div
      className={cn(styles.disclaimerContainer, className)}
      role="alert"
      aria-live="polite"
    >
      <h3 className={styles.disclaimerTitle}>Important Disclaimer</h3>
      <p className={styles.disclaimerText}>
        The AI Lung Cancer Review System provides preliminary information only
        and is
        <b> NOT </b> a substitute for professional medical advice, diagnosis, or
        treatment. The information presented here is generated by AI and{" "}
        <b>MUST</b> be reviewed and confirmed by a qualified physician. Do not
        make any health-related decisions based solely on this information.
        Please consult with your healthcare provider for any medical concerns.
      </p>
    </div>
  );
};

export default Disclaimer;
